version: "3"
services:
  node:
    build: .
    environment:
      ROS_MASTER_URI: http://10.0.2.3:11311
      ROS_IP: 10.0.2.11
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"
    volumes:
      - ./unseen_object_clustering:/workspace/src/unseen_object_clustering
